Our services
leoromero97/communitty-c pull request #9
Opened 2023-08-17 15:45 UTC by georbarbieri

Se modifica :
-index.html : Se agregan secciones de "Our services" y "They chose us"
-Assets : Agregado de imagenes de empresas sin fondos.
-style.css

2023-08-17 20:51 UTC, leoromero97 requested changes
Gran trabajo Geor :muscle: te dejé unos comentarios para optimizar el código, y recordá agregar estilos al contenedor del contenido de cada sección para que no rompa la UI  al modificar los valores del zoom (adjunto ejemplo)
![Uploading bug content.png…]()

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +.our-services__container {
A esta clase falta agregar el ancho máximo:
```
  max-width: 1440px;
  width: 100%;
```

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +
Borrar linea en blanco

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +
Borrar lineas en blanco

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +.they-chose-us__container {
A esta clase también falta agregar el ancho máximo:
```
  max-width: 1440px;
  width: 100%;
```

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +@media screen and (max-width: 768px) {}
¿Se utiliza esta media query?

2023-08-17 20:51 UTC, leoromero97 commented on style.css
> +.our-costumers-say__container {
Esta clase en mobile debería tener habilitado el scroll horizontal, también le falta un contenedor con un ancho máximo de 1440px para que no rompa la layout al hacer zoom

2023-08-17 20:51 UTC, leoromero97 commented on style.css
>  }
Falta agregar linea en blanco al final del archivo

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="" alt="" />
Al final no vamos a tener imágenes de clientes, solo sus nombres y feedback, máximo 5

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="" alt="" />
Eliminar esta etiqueta, ya que no se va a utilizar

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="" alt="" />
Eliminar esta etiqueta, ya que no se va a utilizar

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="" alt="" />
Eliminar esta etiqueta, ya que no se va a utilizar

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="./assets/images/6-removebg-preview.png" alt="" />
Es importante que el nombre de la imagen sea entendible y coincida con el alt, el alt da mejora el SEO y la accesibilidad de la web, describamos lo que hay en la imagen

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +              src="./assets/images/CORDOBA-EMPRENDEDORA-logos-07.png"
Mismo comentario sobre la imagen del cliente, 
¿qué te parece `src="./assets/images/logo-cordoba-emprendedora.png"` ?

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +              alt=""
Agregar descripción de la imagen

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="./assets/images/7-removebg-preview.png" alt="" />
Lo mismo, renombrar imagen y agregar descripción dentro de `alt=""`

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +              alt=""
Lo mismo, renombrar imagen y agregar descripción dentro de `alt=""`

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +            <img src="./assets/images/9-removebg-preview.png" alt="" />
Lo mismo, renombrar imagen y agregar descripción dentro de `alt=""`

2023-08-17 20:51 UTC, leoromero97 commented on index.html
> +              alt=""
Lo mismo, renombrar imagen y agregar descripción dentro de `alt=""`

2023-08-21 23:28 UTC, georbarbieri commented
Leo hice los cambios que me sugeriste, se está modificando la parte de footer

2023-08-22 17:24 UTC, leoromero97 reviewed
Unos detalles y estamos :100:

2023-08-22 17:24 UTC, leoromero97 commented on style.css
> +footer p {
Le falta un espacio entre el final de la web y el copy right, te sugiero agregar un margin-bottom de 50px y un font-weight de 700

2023-08-22 17:24 UTC, leoromero97 commented on style.css
> +  footer p {
Utiliza estas propiedades para que el texto este centrado y no se corte en la UI:

`    text-align: center;
    width: 80%;`

2023-08-22 17:24 UTC, leoromero97 commented on assets/icons/instagram.svg
En la UI se ve raro el ícono, como si fuera muy fino, adjunto ejemplo en FIgma y Preview
![Captura desde 2023-08-22 14-22-07](https://github.com/leoromero97/communitty-c/assets/57498210/5daedc62-ab83-4c5c-aa44-a72808800ea8)
![Captura desde 2023-08-22 14-21-54](https://github.com/leoromero97/communitty-c/assets/57498210/50088e53-1883-42c4-bbab-c555cb0d86b7)

2023-08-22 17:24 UTC, leoromero97 commented on index.html
> +              <img src="./assets/images/team-working.png" alt="" />
Recordá eliminar las imágenes de los clientes, al final no van:

`<img src="./assets/images/team-working.png" alt="" />`

2023-08-24 15:12 UTC, leoromero97 approved these changes
Nice work Geor :rocket:

2023-08-24 15:30 UTC, merged